// examples/angular-app/src/app/app.component.ts
import { Component } from "@angular/core";
import { MindroidRuntime, WebFallbackBridge } from "@mindroid/core";
import { createNetworkPlugin } from "@mindroid/plugin-network";

const runtime = new MindroidRuntime({ bridge: new WebFallbackBridge() });
const network = createNetworkPlugin();
runtime.use(network);

@Component({
  selector: "app-root",
  standalone: true,
  template: `<h1>Mindroid Angular Starter</h1><p>Modules: {{ modules }}</p>`
})
export class AppComponent {
  modules = runtime.getModuleNames().join(", ");
}

// examples/react-app/src/App.tsx
import React, { useEffect, useState } from "react";
import { MindroidRuntime, WebFallbackBridge } from "@mindroid/core";
import { createDeviceInfoPlugin, type DeviceInfo } from "@mindroid/plugin-device-info";

const runtime = new MindroidRuntime({ bridge: new WebFallbackBridge() });
const devicePlugin = createDeviceInfoPlugin();
runtime.use(devicePlugin);

export function App() {
  const [state, setState] = useState<DeviceInfo | null>(null);

  useEffect(() => {
    devicePlugin
      .api()
      .getInfo()
      .then((value) => setState(value))
      .catch(() => setState(null));
  }, []);

  return <pre>{JSON.stringify(state, null, 2)}</pre>;
}
